
a = ['rNZNWvMZZmDDmwqNdZrWTqhJMhhgzggBhzBJBchQzzJJ',
'pHlSVbVbFHgHBzzhQHqg',
'nVsqGpbbtDtTNmrmfZ',
'zrBMnbzBchshsttfbMRBgmJggmmCHGgDhDgNDGHL',
'VddZqQqdvSQMJHJGdCDCDDmH',
'pZWWllPQlPZQvZvwpSVlqlvtfswMRzBbntzRbzbfstsRzF',
'NnjjRlnWNSWWbGwccbcchfPfTvfjfTBBpvmdMjTfvB',
'FVzJtDDJDqTMlmlM',
'gVQZlFLlzHhLGShGww',
'rPZtvtFrFPgWjQvCBlcqMzlqQC',
'QGVDJJnLnVTCJBczqqTM',
'fNSSnmLDSVLhhhSNSLhGSGfVPjrFHwmQwtwWFRWRjWPHrwgt',
'SvmlrVrCvmNhSSVZVCrsgqPfbwGFwwwsflbbGb',
'QHffdnHDDQdMGbgqPwztdPds',
'DjBjWHfQDfTQWTBfpMBQLVmmmcCCcVhCBBBhhCmC',
'trLHFFQHTLHJQrflfCnLLHrRfRRPqSRPbPbbsRGqqGqhjj',
'mcMpNWVVNmNVsSbSJPcGhPRR',
'NpzNgwzZDVNZVWNpHJQLQHtQrZQHrBCl',
'JVCMfgJVrJtMBhhrfVVfhVsjvpFGFgjSSgFdSGGqjvjvqF',
'mHllHlHpmWlDSFqbdSTS',
'nmZRLzQnWVpctMVpQs',
'BrvRzWBPWbRwGRjbbRGrtrfqjCJCjCJgJsZJscFCZcJC',
'MnnnVMVhTMQhsccVfwqFJgqf',
'mMShHHppQmHrrBzwtSbWwR',
'pWWGJMJJwlnZSqjWmvSWZC',
'gtHrLttDtgFjjqRZZCrjpp',
'bFtbTpHFHLbfLFbHVttccttddJGQdJzTwdTzJlMnMBwwJJ',
'JhqHFhVMzJPQcdcVncdc',
'NhgfwSjwCWwltSfnrnRWZdpcPrrRnp',
'NNhlltBjssNBgwLFFvDmDqLzHqBB',
'LnFrnddfrLnMFjWzpFhcWpjpFc',
'ntCwgtNggCqCgCqqPPltvcjjhvmWhmvDzTzDzD',
'lqlVQgVCSPVllVQSNGMHHrdQsHrJJBnMHHJf',
'ZGZcRZNWpcHZhJfbbNblrfrgllNr',
'stBMtzCCsHMfFQjfSSPgtt',
'qmszdsCzMncdGwdWZGvH',
'PccqPqbhvSvvvtWNjTtWsWcscp',
'gRwdDzHJQgHzfdRhgHRffzwsTTjTTCjNjssCpmWWDjtCLW',
'zdRMwdRHhGJwgHlnGGSFvvSrnSrr',
'rRpMJtPwrcCTNNQNMZQm',
'mDWdWVddbbbmBflFhvTHjjQjfZTgZgLLfH',
'bhBbFFnDVhdddFBhdmpJRrzStJmwnPzcsJ',
'RjlpRRWzzRGRmGzlCRRlQjCgtvTJTtJrTPttrWTwhFvvVJFT',
'bSBdLLqbcqcLndLHZNqcZdBDPrVTDDTJSFrJJvVthTwwDS',
'cqVsnBfHffVdqnZccGMmCsGzQmjsjlljgz',
'wMzJhLtwbnMWtHcFCCFqFNNbgq',
'fMlMfjrRRmdmGCGVVCHcVqcVTC',
'MmRRRlvmQWzpvnZpwJ',
'gRmgMRMmRwzzmwHbwcTNqPDVBbPTZVqPNZ',
'fWHphpGFpfJrrhPsNTNZVsNVhT',
'WGfJdvltJJfHrJpRgvMRMSwRznwMmw',
'htJFGsGspCppCFCGthCdpmJmgmWZfqqzWzlWcfgZHgzHlg',
'nwVMjVcVcWlbnBlfWB',
'wcNDTvPPDMFJLLppDGDD',
'hjCBgPbvMvmQDzlWnWjm',
'HrHtgZRRRNwczDWwwDzsQQWW',
'LpTqNtFtLFqHLHRrqgFHffVVBChvhhVPBCPhbPbp',
'CwpbCwjGqSjVllpGCllBfhZZRDPNcPPNvLLLDSDN',
'WshFFWsgTHsdMzQvPczLfLZDZRcLfR',
'rWsJQTMhWWHdsQTgsFJgllClVpqVbqnGblCppCVr',
'gRBSGcBDBSJSvPQwrTFLjggQTQ',
'HMMnHHHZfFVFrrMT',
'HhlhppCNcJzCTtBT',
'CCffCCmRLTsQRPHQQMPF',
'dWdbgcDSNclbbdwdSqHsvHPQPTPJplPMFMGJ',
'DWbDNcqZDSWSccNTVBCzVVfmBVZnVz',
'BnsrrvZwBsBSJrrrqSTgJQjCbCjgbCHDJgJFjQ',
'hLmGlnLmGWcjGDgfFFjQdF',
'hhWPmhPtczWpNRmppzRhLchMsnwZvTMZvVSwwrsNwSsBvr',
'tDCCltNVttJhNGlMPSWdqBqSjM',
'RFQcpcRTpFcnFzdLmLSWjMSSBLSQ',
'jwzzczpFbwnHcDCsthDJJsNbst',
'dLRWTHSwTmTwTcTWvQNVVQCvVvNFps',
'GnBPtBMJBPrjGGJMjrlqChNpNlsnhVFhQsVQ',
'JtMtGJfrJgDJjPjRTZLdFcRZRmwSDH',
'VSccPJSBLgZPDLDQ',
'zfpLMmLsHQGqgQHnDD',
'zdLLMssmrdfhddcVdJtScB',
'VvpTVQHSqSHSHqqHJVmRJVHpgDBwDgjcDDDgZjBZBjwBZbRw',
'PCdssGlstdWslFPfNPrtClGjwBgBJgJNwcjBjBgZwwMBJD',
'tlJldhdhdsdhTqSTqVQqQq',
'VGqTcTqbpPwrjfbl',
'BvntnZNNsLZvLszSnCsvJthlfjTrZwlrjrpPlwlhfwrl',
'QBtNtJLvTsFdQcqWmQRR',
'fjcjhmjBvcvcSvcZ',
'HMwZtRQQpGGRgzMvLnWWnbLlSntlbv',
'JQPzzJHqQRqGMMQwHwzDZZhmmPfjDjmjsCZhPj',
'cBlZZMfBrCBMwBMCvQzTwFbQzPnbwjTbTg',
'WtzpVDzmtthzGFQTbTThnnTQQg',
'sGWstpHdpGDmdHdmGmmmJNstRMrCcBSfBSzNBNRrSRNMcMMv',
'mMPDVBZZLSmRdcFpjr',
'fggGGfbfgQStjjsdbtdt',
'gNqQgCQlNCCJgJHvnvnHMjPHjv',
'bLsRQrQsGQbLrbRZMGgbJJBJFtlFFngJphhcfBBq',
'jjdHCCjfVNmmmNDFcBcpBthcplFDFq',
'jmvvmWVjjHTCVvNjSbQGLrRzwMWsMRwfGG',
'sJNCsCFFCNPhCzlrSvRrvwhRjj',
'MMGMTwpMHGzrGczzlG',
'qVmwgHtDtmCdWCsNFmNJ',
'fmhWhjVjNpqRRJjwRw',
'gnGQGDDCgSsCvPlvPgnPgnPtwqbpHRHqHdJpzpQJJJRJRF',
'wgPGsDGPsZgGgBmBWNZNfLWWrZ',
'WdsCVtjWWWHRRqLLHncC',
'fbSpMSPSZHRRcqlpRc',
'cGMmJmfMPPPccZMNQPWvjTtdTjvgmdtTsggw',
'tPBQhHWBtQHgWQCtLwddcGnfpGpwwnbhVb',
'vqQzTNJJJTvRrTNFJsZrrzFlbbfcnVbbcwmGGGpVzmddcdfd',
'NSSqJvFFFFFQjQCjQDSDPD',
'rQZnVVrZmZmgSWqHrSzHPC',
'LGFLwcMBcllBjFNwGjltggSqSWCCzvNgSqSHtt',
'wdhqqGBwwqGMcDhcwdFFbbJppZbssbfZQsQsdVQm',
'lqBZlsjVTbVqmFrSnTFSvwncPP',
'zQztHfZQtWLJzPFnnQScFcFrvS',
'ftHJWHhfttHWffhtgLNfZDWbdqBqjbVssBDCqCdCsmClGG',
'MlbWFTJQFbFFzRdNjNtjdtBT',
'srwnrsLVHzQPQsjjSQ',
'gLpnwgnwnHCvcHHcvwgCvGFFhWGmFmqMMbQFQFFhlGmJ',
'qqNcJgJccdqhsqgsggdgqgcrtfNWNZzVbvVFzttMfzbVMZ',
'GLlpPpCpwPLDGvrFVWrWWbZt',
'DlRCDDLSjTjDjSRSjPClwnwSHHHQmmQvTJcQgvddHsqdcgmB',
'jmRjRbRQLLZbPnbrcTTHHHNn',
'MfhhmmwtvStrpnJJHc',
'fgqlvfhvFzMwqfvMfFWlmMvLZsdQsZVdCdLZdGQjRzdQjD',
'lTPcDlVdTlVVMSDfTJccVzdlmMgGBmppgBmnHGHqHqQqqQMH',
'ZRjWFPsLNLLrPhWNtnBBvnpGpHGpQmHnmR',
'CtwssCNLrsZWjrjcbfPzwJJJffDbTl',
'cjMvvqpJFqhShNCRQR',
'ldtDgQZDPdzztLZgPTtfbnStfBSbNNSbnbhhSS',
'TDsrzsZZZTFHmVHjcsQW',
'BQmQchrmBddcmZZdpSgrpswWWswVsnnnDJVnnZFnGN',
'TfStMPLTHvbvRVGnHGsNnJWFNV',
'qtvMRMMPbbPMLqRPvRTRzMjSSmprpQdBchlmmgldgjzm',
'nRRnvNPhrbZDLjvS',
'HCszMwcHHcLDrbQDWr',
'ptszqwdMbnnhPBqN',
'QbzhhfbFhBbpbzwwLjLJjSjltL',
'mNndGrSStHJTJLln',
'rDMMNVWdVpCbSbSp',
'tDTSTSTTTTJDwqjWqBWttdjg',
'nNPmVfnGfPNVLmNzfnzPVFMjdpBwWZwZHwBLBqgjqpWH',
'dfGPfVQGVPhGzlmnzSvsSTDJhTbTTrrSRD',
'ZfgtZBptBfRQNQggjjrjjwmwsQJPzrwm',
'TwTGGwTwzzsJzTsH',
'lFvwqFLhFMnqcLlVLMLfptNWppppDBDbDfbFgW',
'mjftBfVPjttmjcSjcPttzJlvnrwvTRrTnvwvlRrHHTHRTR',
'WZDWDNLFWbZbcMDWGZDbNdMCRsnTdTvdnqrHCTrvsRRvwC',
'DQFZLNNgtBJQcBzJ',
'HbZQZFVbQVpQplQZGbGchDffltfLtmdgDjggTmtm',
'zWzRCdnCRBRdJrzDjLhDthjLJTTtjq',
'CPPnwSrRdRSzCGMcZZZMwFwMZF',
'WBQqNQnQllwnWQlvBBMlljHTqqFdGfmTdFfcFTFFcqmP',
'rsRRVrZhrzbtpZRRhFDmPvfFFrfTdFHGvc',
'VtSCtSLbtsZVtttthCbJSWSlJlwJQggWWglvwW',
'QfFLWCvRfSLFCtvtFhNcqDDcGVbhGcqh',
'ZVgrdZZPPZZzPwdjzZhmccsqJGqDdsDDNddD',
'pzzwpgZzZZTznZnjZZzPVRLQLlvfSlQRSpWlCvtSQv',
'RtcHhRMcrHhBrrTNDVBNLqLqQqfBPm',
'wCbWzWbvdWCjbWppmtmNmqmLLsfsNV',
'lwjWdbztgHTgggnnnR',
'flBbzbMfbrTlrMvBCcwPggdmcdmg',
'VDVVRFZRZSFFhQLSGFQhjSVZCgpvPwLCzpdWWzccwdvvvwcC',
'hDHRGQVHHQVRZSQGbqqfNTlbHzrbbsqb',
'MTFdTsZpPTcMpFCPdCBmMBmRfRGBmQgQRRgt',
'vbDSwvhzznnbbhDWnvSzRBgQQLgLQltqtqlmwfGB',
'jVjhfSnNDNbzzWzjWSjrCFNpcHdpTTJddJFpsJcc',
'ZrrZPHfChPdDPVVdDq',
'vFmsbTsmSbbBJssmSBvTmmnTrnrwlWqwVlLrVTLLTWqL',
'JrFbpsvFBMBmzBzFStcRhjZjfCCpZNCtct',
'TGgRrTggwwtvtQtdCdQNqN',
'sJHZJVZHDBpFBZBBNzNdhzdpSzddvqhN',
'VZcvFsJVFvsmvssbcnrwbrnGMbMlRn',
'SdcdWzMJdSMWMddZJdVcmBmwrwqrrnVnVNtr',
'mlQHCfgbjsfQTbfCBNtVhVnntVBnVh',
'HLDslDDmblgHfvLHPJFSZPpDFpFFpdPS',
'qNqPNJvcSzGGPQnGQp',
'bWhbgsshZWBhltthhbWtCsZNjrzpnQnnznnjtQFrjGjVFGnn',
'bRDNddhNdDsZdNChmvDmmwqqvLqwSJDq',
'TnSfPnCSmnSgpSTmfLzfMFLWFJJLWWsBsr',
'jdQjcdqDVVwDcPsPzMRJMLqPqR',
'PGhGchjhtZlTGTHCCb',
'ZZRrJJqSqJwNFFphsGsLPJ',
'blcMCflvTTPFFNpVvsFv',
'CcTlltTmtmMdmCmnlllBDDSDQSwSjRDQSdswjR',
'MCCPNsnQFWbvvTPF',
'CcCVJJhjVJZRtcCclDDlbcbTcGFFDz',
'HpjtVwVZfpjJVhZgCVtLmrBwdMrLsNNsMmdLqB',
'TJTDTnrFzzdWgWGJSSMJwg',
'LhPVttjtLmsPqqqVsVpsjLlgWlwHvGnlHWlgHlGgwvlP',
'mQshLhmsnsqZcqhZqpshsLVpNTNbBfzTRBQdFRzNNFBTdbzR',
'ZGqMLGqvJsJsMJmd',
'PDVQPfPcrrcFrrzrTdgCjSSCzgszmlJjBj',
'PfRtVfttVcWtVJrfbGqvwqLpRRwvpppH',
'HmLmMSnnWnrTrnvpqFCHVGfzVFVHQj',
'ttsstRhhcNwbswNtdwsdNPFfjzQppQPjfGGfQVPCpR',
'bbsDNtDcbhstsSZLDmSSgCmnSS',
'tfwBBLcJVrDnqvLv',
'zmWWJRZhWRRRGRNdgSZGgWTvpnjvrDqvpHjjzrpnrPDnHj',
'NdJmSGZWRhRNsghWTJmdGfQCtllCcFMwffBftsfMQc',
'lTLgTghpGZJDBrnGWnnm',
'VlRwlHttwqmHHbDWHJ',
'twldzCvsRdsFFtRtSczTjSgMcfSpSzTM',
'pBpMBTcSlNtMcTfFCmbPDzCDLb',
'JgrjjJqhGZQrQrZhnJGDDCZfvPDdDzFFdzfmZL',
'QHhqqnrVJJPhHrnGQgwMNwMMctcWRWSBMNtNsW',
'FJrlhpcfDCcFWpNpwWwjNQwz',
'RTTvPdbjWzMbnNNM',
'GRZTGggGgtvjGcqrBcttcDlFhr',
'pMRVdVbbMMMSdWWqHpCTvTjnBBBFFGGB',
'smNfZgcsNrcmzggZszsgRnPGFHjBPTBTjGjPTBNj',
'RmwgsmgfrzzsZtfgZLQQSVWlwbdMhlwdqQ',
'mRRjPmLrrSmzSczSzPgVZFpTCpZCMWrZQMQrZJZT',
'BvdbHNdnJtvBDbqqdBlvwvqpDQMpZQFMCsQCspZTMMCZCF',
'nBlfbfbndJBHPfLRfmhhhhPL',
'ScJDFBNLLbVRqVfZ',
'rWrgmdMgnnBhBtnntf',
'CwBWWMgCwddCgwsQjsrvNvlTJzSNHwNTHFJHzS',
'vnddCrNpCgtjLdSdgCgCCvLnWqDhWBQhHqQHDqBhQHDHNNDl',
'wPTVfVTJmZGJVJGffZBwHMWlWlHlWtbQDqbl',
'mGsJVVJsTVTTmtJVzzTJjdSjjprzCvpSLSCjdnLg',
'zLNggsVHmNNsssLmwzLQZLwDRvGQBqGGDDBBvvDBDqPhRG',
'WrCjbtJdbFhBRglGgjqv',
'JWCJcWcSdWcctnJCcJJJbcbmzwwznmgLzNzmLHmHZMwsZL',
'JRRDNNhhszMTzNMwCG',
'MnHPqmgmHjPnnvjqdmjFLQwLwTLwzTwTdGLCzS',
'BnPPZqmcfqgqnnZmBmqjqhfWVJlRMlhWlRDlVsssbh',
'nmTLTqsvqnwqsvwDPnLHdNVrMMHHCBlmVdmGNV',
'RgRpcJhQRfQZcJbWhQpBHCjVCdjCVGdddMllHp',
'fczbZhzbtcZfgRRBcWSPPwFsLSDswSwTsSzw',
'rbFpzFCVBrrBZCjbCzHHBVdJllGDLsLrDtsswswstGJs',
'QNhNNnNnnQhNWSnRhnJtdpJpJtMDGsGLLtsQ',
'ScmRvNRNnWWvNvNvfpTccjVZbqgZgVzqHjCjTVTVVq',
'BTppwCwBpwwBqnjlHcLBTHnbbSbDthsSSJgsnDDRgJRD',
'FVGzzvrdMGSSsdtZtZgd',
'QvQtvtGFlBLLjLQL',
'gsWWsNMjwgPMPWnMjShHHZSZbmZbbmTSnb',
'rlCvVQrCfqffpVjQRqCCvDDTTTmmZhZTmZhThFmhhZZhqb',
'CDDVJpVfrJJVJLMNzMwWwLwj',
'nHrcsZrssPcBPtQJLJtQQCZQpV',
'GFWzNzNFdNbTMMqbGTqTqzqqdLCpfDQCtRVVCLtdCfQsdCCt',
'TlNqGTWFNmMMszhGsmFTWGFzwHnvSjgPgvgSjllBvBnvwPBB',
'mpMggjgMlmtjtGMwZpcSscBlcsSblhsfSdfs',
'zzPVDRrLrCTQNCzNRTVFNLhBhBSqdQbcfSsJBJdbjJfB',
'RPTRPTVNTFzVrHVDCrTHmHtwMvwWMmtwmGjWgvGv',
'rLMcvfHVfMgLFvfNnBBzwRbBwnrGNs',
'dttJjJCtdjmwzwBCRRCqcs',
'TddDQDJDtQJtcJFpPQHPQMvfQlFL',
'LQSqqpqTCSJcsDcqQMMhnnjMjppZhwHZbZ',
'NRtvtmgmvdBffgtVCBWVRgFbPzHbMHbnwwjMPZfHbPjzPP',
'RNtvCvNdgtNNmldgvCFRNVLsQLqJcQGJJrccGSlDLDLr',
'GdwwqqqwGVtjdPvTCplbHTPbPzPTpp',
'RpLmLLpFfNsgTzclhzClThgH',
'ZFsWZLFZJsNsnWsnRsRfnfJQGBttjdGJjBvvwjdpjjttvj',
'tfPzzLrrdrQlTlvn',
'qJRBhNhNGVRBFRTlnJvCmvmJPCCl',
'VVPDNchNMVFGRMFcRVBjsZZcttSLSZzzStcWtZ',
'pTrwTrnjtttjprTSTNTQfcjcgPsPZfPgjdgdsQ',
'mCmCzvzhmJDHzJDbhFCDPsgddcsfcdsbdgVRpdVs',
'zqJzFCDhmqvGhMmCvmGhMCGJnSlnllSBLllLMtNpWtpNBnlt',
'JBhJrFLhGrnJZrlcbffndnggfggf',
'jqmWMGGSsqCsmpjmsDQzlcHgbtdzjjlVfctjHV',
'GWSmSCspCsMSpRmSmqMMCBvFLJLhTTwFhRFLLBTwrv',
'BCdWccqcqpQqrsNgGsWMgfNW',
'lFttLzzLwnfsLrsNsNLG',
'zjNlznlwvRPZnltwvPFnZRCbmjCcqjpcpQcqVVdbdVBm',
'CwTbbCGNFHtHwwjSjJpzjLMdMMzT',
'rscqqVvWgWrZMjrlmSzzmLrM',
'WPqqZnPqgncnBQQVRbCDwRHGSFHPwRNw',
'ZQnZwWjFvdsHwBJltfmfSlsqlJ',
'gPprhMDTpMpPMVNqNRqNlJhltJdJ',
'pLGCcCrgppCrVcMpdzjvzvjLwQQzFjwzHF',
'NmmmvfqcvmLSQhCLvtvL',
'TVlWTZVJZJsFbwWbQQhtQgLFCnSgghLt',
'hZJTJZhwZlRJrJWHVlblMBffmqfdNMjdGdBBqqcH',
'GJJfLfptGqqqnsVqVVjjDnNc',
'mZPSvPmBCdmwdCLDshSbRnnDDhRL',
'gvBrBvPBPPZCTLZmwmrgQdwfTJMHGzHfWffJzFzttHWFzW',
'sBMvmzWzmFmNWJfffZNLfbqZbtZq',
'jRQVRnhhppnVhjgnDLttLqbLqLQfDLss',
'jRRgpGVGhwhnspgpRppwSnBvMMcWvGczGJJHdmHJmJFF',
'VCLHFwHMhLghHHWhFFgWNMMVzmdmbvWdJqBPJPPBppqmBdzm',
'SRTsjGZTsZZnSnGZGqdBmrqPvmqqqsPpmv',
'GvQSGtZSQllVhtLMcLLNMH',
'GsNdWpdVWGSHjFCWCqFFgqngvW',
'mRQTcrLRmZTPRLPZfqqqHbDDDgFvFnvqzQ',
'hfZHrwwmcZRwlLfwlmrRjMJJsVjslVNBGNjpVBBG',
'pllpztRqBBvvGPpG',
'QQhhZQbVcZQTPMWWGbvvbMHM',
'cwgCQCLZChQwwLZVzCrzzqNCzrDqdFPF',
'bgcLPvvpcbdsbpSsHRTCqsRfWfsHRm',
'lZlQtthrnlVMmTHqqqqHSChB',
'rDtlzttnlSNrMtQjZVrcgGDLLddcdcpPgPGJJd',
'jvGbvLLQDSGlRmmSLjlDmRQggFBrMCwWdsBFWBFjdrrWrr',
'PpTfcPZpNTVNpHzTzzzpPJhBcwrrhFsrMdFcMCBFhgMF',
'JTTqdtfzfzJpqffNdTTHGtQRnmDQGGLQQlQRbblD',
'CQQCshCMwgQhMdjWJFBPpbjgmmWj',
'SNNvcGNSZSTDtGDcczJJBmzbjBJjmppbppms',
'cDtfDVNTGGGNNrwLLwHdqLhfLs',
'ngghZCChzhNjjNbbJfdh',
'slPPRLlBBlVRMvRllLLHvcpcdFfJjvdFpfHfcZ',
'RDZPZBLmPVWDVrQtnzSTmgTwmTSg']

def comparegroups(a,b,c):
    s = ""
    t = ""
    for x in a:
        for y in b:
            for z in c:
                if x == y and x == z:
                    t=x
        s=s+t
    print (s)


def comparebags(a,b):
    s = ""
    t = ""
    for x in a:
        for y in b:
            if x == y:
                t=x
        s=s+t
    print (s)

c = 0
lengtharray = len (a)

while c < lengtharray:

    length = int (len(a[c]))
    half = int(len(a[c])/2)

    x = a[c][0:half]
    y = a[c][half:length]

    comparebags(x,y)

    c = c+1

else:
    c = 0
    print ("******************************Bags Finished******************************")

while c < lengtharray:

    x = a[c]
    y = a[c+1]
    z = a[c+2]

    comparegroups(x,y,z)

    c = c+3

else: 
    print ("******************************Groups Finished******************************")